#!/usr/bin/env bash
# Fast-tier: exercise retroconsole-seed's managed-home override policy against a
# fabricated "old /home/retro" and assert the locked M10 policy holds:
#   * managed files/keys are force-overwritten to the packaged value;
#   * es_settings.xml + user data (ROMs/savestates) are NEVER touched — a
#     deliberate user edit survives;
#   * a second run is idempotent (same content/mode/owner, no errors);
#   * the live-guard (/etc/retroconsole-live) short-circuits with no changes.
#
# DESTRUCTIVE: wipes /home/retro and /usr/share/retroconsole/skel. It is for
# throwaway Arch CI containers ONLY — hence the opt-in guard below. Run as root
# (the seed installs files as user 'retro' and re-execs via sudo when not root).
# CI runs it via docker; locally:
#   docker run --rm -v "$PWD":/build:ro -w /build archlinux:latest bash -c '
#     pacman -Sy --noconfirm --needed base-devel >/dev/null &&
#     SEED_RECONCILE_TEST=1 scripts/test-seed-reconcile.sh'
set -uo pipefail

if [[ ${SEED_RECONCILE_TEST:-} != 1 ]]; then
    echo "Refusing to run: this test WIPES /home/retro and /usr/share/retroconsole/skel." >&2
    echo "It is for throwaway Arch CI containers only. Set SEED_RECONCILE_TEST=1 to proceed." >&2
    exit 2
fi

cd "$(dirname "$0")/.."
SEED="${PWD}/packages/retroconsole-config/retroconsole-seed"
SKEL=/usr/share/retroconsole/skel/home/retro
HOME_DIR=/home/retro
# #62/#63: the packaged empty stub (seed reads it here) and the STOCK bundled
# ES-DE systems file the seed must force-empty.
STUB=/usr/share/retroconsole/es-de/es_systems-empty.xml
ESDE_SYSTEMS=/usr/share/es-de/resources/systems/linux/es_systems.xml

fail=0
ok()  { echo "  ok   $*"; }
bad() { echo "  FAIL $*" >&2; fail=1; }

# --- setup -----------------------------------------------------------------
id retro &>/dev/null || useradd -m retro || { echo "setup: useradd retro failed" >&2; exit 1; }
rm -rf "${HOME_DIR}" /usr/share/retroconsole/skel /usr/share/retroconsole/es-de
rm -f "${ESDE_SYSTEMS}"
mkdir -p "${HOME_DIR}"

# Packaged skel (the managed defaults), generated exactly as the build does.
scripts/gen-config-skel.sh profile/airootfs/home/retro "${SKEL}" \
    || { echo "setup: skel generation failed" >&2; exit 1; }

# #62/#63: install the packaged empty stub where the seed reads it (mirrors the
# PKGBUILD), and fabricate a STOCK multi-system bundled ES-DE file the seed must
# force-overwrite with that stub. (CI has no emulationstation-de installed.)
install -Dm644 packages/retroconsole-config/es_systems-empty.xml "${STUB}" \
    || { echo "setup: stub install failed" >&2; exit 1; }
mkdir -p "$(dirname "${ESDE_SYSTEMS}")"
printf '<?xml version="1.0"?>\n<systemList>\n  <system><name>atari2600</name></system>\n  <system><name>c64</name></system>\n  <system><name>nes</name></system>\n</systemList>\n' \
    > "${ESDE_SYSTEMS}"

# Fabricate a stale/divergent "old home".
mkdir -p "${HOME_DIR}/ROMs/tools" "${HOME_DIR}/ES-DE/custom_systems" \
         "${HOME_DIR}/.config/retroarch" "${HOME_DIR}/ES-DE/settings" \
         "${HOME_DIR}/ROMs/nes"
# managed — must be force-overwritten:
printf 'STALE bash_profile - must be replaced\n'                 > "${HOME_DIR}/.bash_profile"
printf '#!/bin/bash\necho STALE shell launcher\n'                > "${HOME_DIR}/ROMs/tools/Shell.sh"
printf '<stale-systems/>\n'                                      > "${HOME_DIR}/ES-DE/custom_systems/es_systems.xml"
printf 'joypad_autoconfig_dir = "/wrong/old/path"\nvideo_fullscreen = "true"\n' \
                                                                 > "${HOME_DIR}/.config/retroarch/retroarch.cfg"
# user-reachable — must NEVER be touched:
MARK="USER_EDIT_MARKER_$$_keepme"
printf '<settings><edit>%s</edit></settings>\n' "${MARK}"        > "${HOME_DIR}/ES-DE/settings/es_settings.xml"
printf 'rom-bytes-%s\n' "${MARK}"                               > "${HOME_DIR}/ROMs/nes/MyGame.nes"
printf 'savestate-bytes-%s\n' "${MARK}"                         > "${HOME_DIR}/ROMs/nes/MyGame.state"
# #62/#64 ROM-dir fixtures (dir modes/existence only; user content untouched):
#  - a CURATED dir at the wrong mode -> seed reconciles it to retro:retro 0777
mkdir -p "${HOME_DIR}/ROMs/megadrive"; chmod 0700 "${HOME_DIR}/ROMs/megadrive"
#  - an EMPTY non-curated dir (only ES-DE's systeminfo.txt) -> seed sweeps it
mkdir -p "${HOME_DIR}/ROMs/atari2600"
printf 'auto-generated by ES-DE\n'                             > "${HOME_DIR}/ROMs/atari2600/systeminfo.txt"
#  - a non-curated dir holding a REAL ROM -> seed keeps it, untouched
mkdir -p "${HOME_DIR}/ROMs/c64"
printf 'rom-bytes-%s\n' "${MARK}"                              > "${HOME_DIR}/ROMs/c64/Boulder Dash.crt"
printf 'auto-generated by ES-DE\n'                             > "${HOME_DIR}/ROMs/c64/systeminfo.txt"
chown -R retro:retro "${HOME_DIR}"

# --- run #1 ----------------------------------------------------------------
echo ":: run #1 — reconcile a divergent home"
bash "${SEED}" || bad "seed exited non-zero on run #1"

cmp -s "${SKEL}/.bash_profile" "${HOME_DIR}/.bash_profile" \
    && ok ".bash_profile force-overwritten" || bad ".bash_profile not reconciled"
cmp -s "${SKEL}/ES-DE/custom_systems/es_systems.xml" "${HOME_DIR}/ES-DE/custom_systems/es_systems.xml" \
    && ok "es_systems.xml force-overwritten" || bad "es_systems.xml not reconciled"
cmp -s "${SKEL}/ROMs/tools/Shell.sh" "${HOME_DIR}/ROMs/tools/Shell.sh" \
    && ok "Shell.sh launcher force-overwritten" || bad "Shell.sh not reconciled"
meta=$(stat -c '%U:%G %a' "${HOME_DIR}/ROMs/tools/Shell.sh")
[[ ${meta} == "root:root 755" ]] && ok "Shell.sh is root:root 0755" || bad "Shell.sh meta='${meta}' (want 'root:root 755')"
grep -qx 'joypad_autoconfig_dir = "/usr/share/libretro/autoconfig"' "${HOME_DIR}/.config/retroarch/retroarch.cfg" \
    && ok "joypad_autoconfig_dir key forced" || bad "joypad_autoconfig_dir not forced"
# M11/#18: the fabricated cfg above has no menu combo, so this exercises the
# ensure_kv_force APPEND branch — the OTA path that gives an old box menu access.
grep -qx 'input_menu_toggle_gamepad_combo = "9"' "${HOME_DIR}/.config/retroarch/retroarch.cfg" \
    && ok "input_menu_toggle_gamepad_combo key forced (Down+Select)" || bad "menu combo key not forced"
# #19/#20: shader browser pointed at the bundled pack so Quick Menu -> Shaders is
# populated on OTA boxes without an online-updater download.
grep -qx 'video_shader_dir = "/usr/share/libretro/shaders/"' "${HOME_DIR}/.config/retroarch/retroarch.cfg" \
    && ok "video_shader_dir key forced (bundled shader pack)" || bad "video_shader_dir not forced"
grep -qx 'video_fullscreen = "true"' "${HOME_DIR}/.config/retroarch/retroarch.cfg" \
    && ok "unmanaged retroarch key preserved" || bad "unmanaged retroarch key lost"

grep -q "${MARK}" "${HOME_DIR}/ES-DE/settings/es_settings.xml" \
    && ok "es_settings.xml user edit survived" || bad "es_settings.xml was clobbered"
grep -q "${MARK}" "${HOME_DIR}/ROMs/nes/MyGame.nes" \
    && ok "user ROM untouched" || bad "user ROM changed"
grep -q "${MARK}" "${HOME_DIR}/ROMs/nes/MyGame.state" \
    && ok "savestate untouched" || bad "savestate changed"

# #62/#63: the STOCK bundled ES-DE systems file is force-emptied to the stub,
# so ES-DE knows only the curated set and can't flood ROMs/ from its menu.
cmp -s "${STUB}" "${ESDE_SYSTEMS}" \
    && ok "bundled es_systems.xml force-emptied to stub" || bad "bundled es_systems.xml not emptied"

# #62/#64: curated dir reconciled to 0777 (dir only); empty non-curated dir
# swept; non-curated dir with a real ROM preserved untouched.
dirmeta=$(stat -c '%U:%G %a' "${HOME_DIR}/ROMs/megadrive")
[[ ${dirmeta} == "retro:retro 777" ]] \
    && ok "curated dir megadrive reconciled to retro:retro 0777" \
    || bad "megadrive meta='${dirmeta}' (want 'retro:retro 777')"
[[ ! -e "${HOME_DIR}/ROMs/atari2600" ]] \
    && ok "empty non-curated dir (systeminfo.txt only) swept" || bad "empty non-curated dir not swept"
[[ -d "${HOME_DIR}/ROMs/c64" && -f "${HOME_DIR}/ROMs/c64/Boulder Dash.crt" ]] \
    && ok "non-curated dir with a real ROM preserved" || bad "non-curated dir with a ROM was removed"
grep -q "${MARK}" "${HOME_DIR}/ROMs/c64/Boulder Dash.crt" 2>/dev/null \
    && ok "preserved non-curated ROM untouched" || bad "preserved non-curated ROM changed"

# --- idempotency: run #2 leaves content/mode/owner identical ----------------
# (mtime is deliberately excluded — install(1) always rewrites it.)
manifest() {
    find "${HOME_DIR}" -exec stat -c '%n %a %U:%G %s' {} \; | sort
    ( cd "${HOME_DIR}" && find . -type f -exec sha256sum {} \; | sort )
}
before=$(manifest)
echo ":: run #2 — idempotency"
bash "${SEED}" || bad "seed exited non-zero on run #2"
after=$(manifest)
if [[ ${before} == "${after}" ]]; then
    ok "second run idempotent (content/mode/owner unchanged)"
else
    bad "second run changed the home:"
    diff <(printf '%s\n' "${before}") <(printf '%s\n' "${after}") | head >&2
fi
# The bundled ES-DE file lives outside ${HOME_DIR}, so the manifest above can't
# see it — re-assert it stayed emptied across run #2 (the stub-apply is a no-op
# bar mtime, which is fine; this catches a future non-idempotent regression).
cmp -s "${STUB}" "${ESDE_SYSTEMS}" \
    && ok "bundled es_systems.xml still emptied after run #2" || bad "bundled es_systems.xml drifted on run #2"

# --- #62/#64 symlink safety: the ROM loops must NEVER act through a symlink ---
# A symlink placed under ROMs/ must not let the root-run seed chmod/chown its
# target (curated name) or delete a file inside it (non-curated) — both loops
# would otherwise follow the link and touch data outside the curated ROM dir.
echo ":: symlink-safety — seed must not reconcile/sweep through a symlinked ROM dir"
ext_cur=$(mktemp -d); chmod 0755 "${ext_cur}"
ext_non=$(mktemp -d); chmod 0755 "${ext_non}"
printf 'auto-generated by ES-DE\n'                             > "${ext_non}/systeminfo.txt"
rm -rf "${HOME_DIR}/ROMs/psx"                                   # seed materialized it as a real dir
ln -s "${ext_cur}" "${HOME_DIR}/ROMs/psx"                       # curated NAME, but a symlink
ln -s "${ext_non}" "${HOME_DIR}/ROMs/extlink"                   # non-curated symlink, "empty" target
chown -h retro:retro "${HOME_DIR}/ROMs/psx" "${HOME_DIR}/ROMs/extlink"
bash "${SEED}" || bad "seed exited non-zero on symlink-safety run"
symmeta=$(stat -c '%a' "${ext_cur}")
[[ ${symmeta} == 755 ]] \
    && ok "curated symlink target left at 0755 (reconcile skipped the link)" \
    || bad "curated symlink target mode='${symmeta}' (want 755 — reconcile followed the link)"
[[ -L "${HOME_DIR}/ROMs/psx" ]] && ok "curated symlink preserved" || bad "curated symlink was clobbered"
[[ -f "${ext_non}/systeminfo.txt" ]] \
    && ok "sweep did not delete through the non-curated symlink" \
    || bad "sweep deleted a file through a non-curated symlink"
[[ -L "${HOME_DIR}/ROMs/extlink" ]] && ok "non-curated symlink kept (not swept)" || bad "non-curated symlink was swept"
rm -rf "${ext_cur}" "${ext_non}"
rm -f "${HOME_DIR}/ROMs/psx" "${HOME_DIR}/ROMs/extlink"

# --- live guard -------------------------------------------------------------
echo ":: live-guard — must make no changes"
printf 'CORRUPT managed file\n' > "${HOME_DIR}/.bash_profile"
touch /etc/retroconsole-live
bash "${SEED}"; rc=$?
rm -f /etc/retroconsole-live
[[ ${rc} -eq 0 ]] && ok "live-guard exits 0" || bad "live-guard exit=${rc} (want 0)"
grep -qx 'CORRUPT managed file' "${HOME_DIR}/.bash_profile" \
    && ok "live-guard made NO changes" || bad "live-guard modified the home"

# --- result -----------------------------------------------------------------
if [[ ${fail} -eq 0 ]]; then
    echo ":: seed/reconcile policy OK"
else
    echo ":: seed/reconcile policy FAILED" >&2
    echo "--- /var/log/retroconsole-seed.log ---" >&2
    cat /var/log/retroconsole-seed.log >&2 2>/dev/null || true
fi
exit "${fail}"
