[global]
   workgroup = WORKGROUP
   server string = RetroConsole
   server role = standalone server
   map to guest = Bad User
   guest account = retro
   security = user
   server min protocol = SMB2
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes

[ROMs]
   path = /home/retro/ROMs
   comment = RetroConsole ROMs
   browseable = yes
   writable = yes
   guest ok = yes
   guest only = yes
   force user = retro
   create mask = 0644
   directory mask = 0755
